_BASE_: './Base-RCNN-FPN-KINS2020.yaml'
MODEL:
  WEIGHTS: "https://dl.fbaipublicfiles.com/detectron2/new_baselines/mask_rcnn_R_50_FPN_400ep_LSJ/42019571/model_final_14d201.pkl"
  MASK_ON: True
  RESNETS:
    DEPTH: 50
  ROI_MASK_HEAD:
    NAME: ShapeFormerv2
SHAPEFORMER:
  SEARCHER_PRETRAINED: ../data/train_outputs/6_shapeformer/release/prior_models/cvqvae_kins2020_K128/cvqvae_kins2020_K128.pt
OUTPUT_DIR: ../data/train_outputs/6_shapeformer/release/main_models/shapeformer_release_R50_FPN_kins2020/
