_BASE_: './shapeformerv2_R50_FPN_kins2020_6ep_bs1.yaml'
MODEL:
  WEIGHTS: "https://dl.fbaipublicfiles.com/detectron2/new_baselines/mask_rcnn_R_101_FPN_400ep_LSJ/42073830/model_final_f96b26.pkl" 
  RESNETS:
    DEPTH: 101
OUTPUT_DIR: ../data/train_outputs/6_shapeformer/release/main_models/shapeformer_release_R101_FPN_kins2020/
